AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: mlops

Resources:
  #================================================================================
  # IAM
  #================================================================================
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExecutionRoleName: !Sub ${ProjectName}-ExecutionRole
      TemplateURL: https://aws-mlops-workshop.s3-eu-west-1.amazonaws.com/reviews/stack/templates/iam_template.yaml
  #================================================================================
  # SAGEMAKER
  #================================================================================
  SAGEMAKER:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NotebookInstanceName: !Sub ${ProjectName}-notebooks
        NotebookInstanceType: ml.m5.xlarge
        NotebookInstanceRoleArn: !GetAtt IAM.Outputs.ExecutionRoleArn
      TemplateURL: https://raw.githubusercontent.com/michaelhoarau/end-to-end-transformers/master/0_cfn_templates/sagemaker_template.yaml

  #================================================================================
  # LAMBDA
  #================================================================================
  LAMBDA:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        LambdaRoleArn: !GetAtt IAM.Outputs.ExecutionRoleArn
      TemplateURL: https://aws-mlops-workshop.s3-eu-west-1.amazonaws.com/reviews/stack/templates/lambda_template.yaml