AWSTemplateFormatVersion: 2010-09-09
Description: Create SageMaker Notebook Instance

Parameters:
  NotebookInstanceName:
    Type: String
  NotebookInstanceType:
    Type: String
  NotebookInstanceRoleArn:
    Type: String

Resources:
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !Ref NotebookInstanceRoleArn
      VolumeSizeInGB: 50
      DefaultCodeRepository: 'https://github.com/michaelhoarau/end-to-end-transformers.git'

Outputs:
  SageMakerNotebookInstance:
    Value: !Ref SageMakerNotebookInstance
